// MyLibrary data file
// CTF collections are separated by competition. Each writeup keeps its challenge category as metadata.
// Only completed writeups with a documented final flag are published.

window.WRITEUP_LIBRARY = [
  {
    "id": "boroctf",
    "name": "boroCTF Writeups",
    "shortName": "boroCTF",
    "icon": "🧪",
    "accent": "rgba(104, 245, 255, 0.72)",
    "accentSoft": "rgba(104, 245, 255, 0.28)",
    "description": "A dedicated boroCTF cabinet containing Web, Crypto, Forensics, Pwn, and Reverse casefiles imported from the original notes.",
    "tags": [
      "Web",
      "Crypto",
      "Forensics",
      "Pwn",
      "Reverse"
    ],
    "writeups": [
      {
        "title": "boroGPT",
        "ctf": "boroCTF",
        "points": "",
        "solves": "",
        "solveTime": "Documented",
        "tags": "SSTI, JSON API, Dev Mode, File Read",
        "skills": "API Testing · Template Injection · curl · Python Object Traversal",
        "date": "2026-06-10",
        "difficulty": "Medium",
        "summary": "Submitted a malicious template to the render API in dev mode and used template object traversal to read /flag.txt.",
        "url": "./web/borogpt.html",
        "category": "Web"
      },
      {
        "title": "Jay W. Tee",
        "ctf": "boroCTF",
        "points": "",
        "solves": "",
        "solveTime": "Documented",
        "tags": "JWT, alg:none, Auth Bypass",
        "skills": "JWT Analysis · Cookie Testing · Access Control · curl",
        "date": "2026-06-18",
        "difficulty": "Easy",
        "summary": "Forged an unsigned JWT by changing alg to none and role to admin, then accessed the admin page.",
        "url": "./web/jay-w-tee.html",
        "category": "Web"
      },
      {
        "title": "Kobeni's Dashboard",
        "ctf": "boroCTF",
        "points": "",
        "solves": "210",
        "solveTime": "Documented",
        "tags": "ImageMagick, SVG, LFI, File Read",
        "skills": "curl · SVG Payloads · ImageMagick Abuse · Enumeration",
        "date": "2026-06-14",
        "difficulty": "Medium",
        "summary": "Used an ImageMagick SVG label:@ primitive to read local files from a file-upload image processor.",
        "url": "./web/kobenis-dashboard.html",
        "category": "Web"
      },
      {
        "title": "NERV",
        "ctf": "boroCTF",
        "points": "",
        "solves": "",
        "solveTime": "Documented",
        "tags": "SSTI, Jinja2, File Read",
        "skills": "Flask/Jinja SSTI · curl · Linux Enumeration · Command Execution",
        "date": "2026-06-17",
        "difficulty": "Medium",
        "summary": "Abused a Jinja-style template injection in the admin report query to locate and read /flag.txt.",
        "url": "./web/nerv.html",
        "category": "Web"
      },
      {
        "title": "OH NO!!!",
        "ctf": "boroCTF",
        "points": "",
        "solves": "",
        "solveTime": "Documented",
        "tags": "Ghidra, Lookup Table, Cumulative Indexing",
        "skills": "Static Analysis · Algorithm Reversal · String Analysis · Ghidra",
        "date": "2026-06-20",
        "difficulty": "Medium",
        "summary": "Reversed a bike-lock binary that dynamically generated the flag from cumulative digit offsets into a lookup string.",
        "url": "./reverse/oh-no-bike-lock.html",
        "category": "Reverse"
      },
      {
        "title": "Humanity Impossible",
        "ctf": "boroCTF",
        "points": "",
        "solves": "",
        "solveTime": "Documented",
        "tags": "Pwntools, Automation, Hex Parsing",
        "skills": "Remote Scripting · Regex · Hex Conversion · Pwntools",
        "date": "2026-06-21",
        "difficulty": "Easy",
        "summary": "Automated a remote service that requested a changing hex-sized payload on every round.",
        "url": "./pwn/humanity-impossible.html",
        "category": "Pwn"
      },
      {
        "title": "I Can Fix This",
        "ctf": "boroCTF",
        "points": "",
        "solves": "",
        "solveTime": "Documented",
        "tags": "Stack Overflow, gets(), State Manipulation",
        "skills": "pwntools · Stack Layout · Buffer Overflow · Logic Abuse",
        "date": "2026-06-22",
        "difficulty": "Beginner",
        "summary": "Used an overflow in gets() to overwrite an adjacent stack string so the program’s comparison succeeds without code execution.",
        "url": "./pwn/i-can-fix-this.html",
        "category": "Pwn"
      },
      {
        "title": "Babel's Vault",
        "ctf": "boroCTF",
        "points": "300",
        "solves": "185",
        "solveTime": "Documented",
        "tags": "Custom Cipher, Base55, RGB Indexing",
        "skills": "Python Reversal · Base Conversion · Code Review · Index Decoding",
        "date": "2026-06-15",
        "difficulty": "Medium",
        "summary": "Reversed a Library-of-Babel-style seed generator and decoded RGB triples as indexes into AUTHORSNOTE.txt.",
        "url": "./crypto/babels-vault.html",
        "category": "Crypto"
      },
      {
        "title": "Flight",
        "ctf": "boroCTF",
        "points": "",
        "solves": "",
        "solveTime": "Documented",
        "tags": "Wingdings, Symbol Cipher, Gaster Hint",
        "skills": "Encoding Analysis · Font-based Cipher · Pattern Recognition · Flag Recovery",
        "date": "2026-06-24",
        "difficulty": "Easy",
        "summary": "Decoded a Wingdings-style ciphertext using the “dark, darker, yet darker” hint to recover the flag.",
        "url": "./crypto/flight.html",
        "category": "Crypto"
      },
      {
        "title": "Johnny Boy",
        "ctf": "boroCTF",
        "points": "",
        "solves": "",
        "solveTime": "Documented",
        "tags": "John the Ripper, ZIP, Wordlists, AES ZIP",
        "skills": "zip2john · John Rules · 7z Extraction · Wordlist Filtering",
        "date": "2026-06-11",
        "difficulty": "Medium",
        "summary": "Read the archive filenames as a hint, cracked encrypted ZIPs with John, then used a chip-themed targeted wordlist for the final password.",
        "url": "./crypto/johnny-boy.html",
        "category": "Crypto"
      },
      {
        "title": "File File Crocodile",
        "ctf": "boroCTF",
        "points": "",
        "solves": "",
        "solveTime": "Documented",
        "tags": "PNG Polyglot, ZIP Repair, File Signatures",
        "skills": "binwalk · File Signature Analysis · Python Bytes · Archive Recovery",
        "date": "2026-06-23",
        "difficulty": "Easy",
        "summary": "Recovered a damaged ZIP archive appended after a PNG, repaired its signature, and unlocked it with the crocodile-themed password.",
        "url": "./forensics/file-file-crocodile.html",
        "category": "Forensics"
      },
      {
        "title": "Judgment of Solomon",
        "ctf": "boroCTF",
        "points": "",
        "solves": "",
        "solveTime": "Documented",
        "tags": "QR Repair, Hex Dump, Image Reconstruction",
        "skills": "PIL · OpenCV · QR Anatomy · Data Cleaning",
        "date": "2026-06-13",
        "difficulty": "Hard",
        "summary": "Removed a fake embedded flag, reconstructed a 66×66 RGB image, repaired a damaged QR code, and decoded the real flag.",
        "url": "./forensics/judgment-of-solomon.html",
        "category": "Forensics"
      },
      {
        "title": "Phantom",
        "ctf": "boroCTF",
        "points": "",
        "solves": "",
        "solveTime": "Documented",
        "tags": "PCAP, TCP Timestamp, XOR, Covert Channel",
        "skills": "Wireshark · Packet Analysis · XOR Decoding · Python",
        "date": "2026-06-16",
        "difficulty": "Medium",
        "summary": "Ignored noisy payloads and decoded data hidden in TCP timestamp options using XOR key 0x2a.",
        "url": "./forensics/phantom.html",
        "category": "Forensics"
      },
      {
        "title": "Retinal Burn",
        "ctf": "boroCTF",
        "points": "",
        "solves": "",
        "solveTime": "Documented",
        "tags": "Steganography, RGB Channels, Contrast Stretch",
        "skills": "PIL · NumPy · Channel Analysis · Image Enhancement",
        "date": "2026-06-12",
        "difficulty": "Easy",
        "summary": "Amplified tiny near-white RGB differences and isolated a blue-channel signal to reveal the hidden flag.",
        "url": "./forensics/retinal-burn.html",
        "category": "Forensics"
      }
    ]
  },
  {
    "id": "kitctf",
    "name": "kitCTF / GPNCTF Writeups",
    "shortName": "kitCTF",
    "icon": "🍳",
    "accent": "rgba(105, 255, 188, 0.76)",
    "accentSoft": "rgba(105, 255, 188, 0.26)",
    "description": "A separate kitCTF/GPNCTF cabinet with solved Reverse, Crypto, Web, Pwn, Misc, and Forensics challenges only.",
    "tags": [
      "Reverse",
      "Crypto",
      "Web",
      "Pwn",
      "Misc",
      "Forensics"
    ],
    "writeups": [
      {
        "title": "Auto Cooker",
        "ctf": "kitCTF / GPNCTF",
        "points": "",
        "solves": "",
        "solveTime": "Documented",
        "tags": "Reverse, Ghidra, XOR, Nibble Swap, Array Reversal",
        "skills": "Static Analysis · Ghidra Decompilation · XOR Reversal · Nibble Swapping",
        "date": "2026-06-24",
        "difficulty": "Easy",
        "summary": "Reversed a cooking-themed flag checker by undoing XOR salting, nibble swapping, array reversal, and the final target comparison.",
        "url": "./kitctf/auto-cooker.html",
        "category": "Reverse"
      },
      {
        "title": "kitCTF / specCTF",
        "ctf": "kitCTF / GPNCTF",
        "points": "",
        "solves": "",
        "solveTime": "Documented",
        "tags": "Reverse, Spectre, Hash Inversion, Side Channel, MurmurHash",
        "skills": "Binary Reversing · Hash Inversion · Modular Arithmetic · Static Analysis",
        "date": "2026-06-24",
        "difficulty": "Medium",
        "summary": "Avoided the Spectre red herring by reversing an invertible 64-bit hash and decoding the global ENC array directly.",
        "url": "./kitctf/kitctf-spectf.html",
        "category": "Reverse"
      },
      {
        "title": "Königsberg Delivery Problem",
        "ctf": "kitCTF / GPNCTF",
        "points": "100",
        "solves": "",
        "solveTime": "Documented",
        "tags": "Reverse, Ghidra, CFG, Graph Theory, State Machine",
        "skills": "Control-Flow Graph Analysis · State Machine Reversal · Graph Traversal · Payload Generation",
        "date": "2026-06-24",
        "difficulty": "Medium",
        "summary": "Converted a giant CFG/state-machine validator into a graph traversal problem and generated the required 250-value semicolon payload.",
        "url": "./kitctf/konigsberg-delivery-problem.html",
        "category": "Reverse"
      },
      {
        "title": "easy-dsa",
        "ctf": "kitCTF / GPNCTF",
        "points": "",
        "solves": "",
        "solveTime": "Documented",
        "tags": "Crypto, ECDSA, P-521, HNP, LLL",
        "skills": "ECDSA Math · Nonce Bias Analysis · Lattice Reduction · CVP",
        "date": "2026-06-24",
        "difficulty": "Hard",
        "summary": "Exploited undersized SHA-256-derived ECDSA nonces on P-521 as a Hidden Number Problem and recovered the signing key with LLL/CVP.",
        "url": "./kitctf/easy-dsa.html",
        "category": "Crypto"
      },
      {
        "title": "Fortune 2",
        "ctf": "kitCTF / GPNCTF",
        "points": "",
        "solves": "",
        "solveTime": "Documented",
        "tags": "Crypto, NTRU-like, Polynomial, Modulo Leak, Encoding",
        "skills": "Source Review · Modular Arithmetic · Polynomial Scheme Analysis · Remote Scripting",
        "date": "2026-06-24",
        "difficulty": "Easy",
        "summary": "Bypassed the NTRU-looking structure by reducing ciphertext coefficients modulo 3, which directly revealed the encoded message.",
        "url": "./kitctf/fortune-2.html",
        "category": "Crypto"
      },
      {
        "title": "Restaurant Builder",
        "ctf": "kitCTF / GPNCTF",
        "points": "",
        "solves": "",
        "solveTime": "Documented",
        "tags": "Web, FastAPI, Pydantic, RCE, Exfiltration",
        "skills": "Source Review · Python Internals · Pydantic Abuse · HTTP Testing",
        "date": "2026-06-24",
        "difficulty": "Intro",
        "summary": "Abused Pydantic create_model forward-reference evaluation and typing.Literal to exfiltrate the FLAG environment variable through the schema endpoint.",
        "url": "./kitctf/restaurant-builder.html",
        "category": "Web"
      },
      {
        "title": "Recipe for Disaster",
        "ctf": "kitCTF / GPNCTF",
        "points": "",
        "solves": "",
        "solveTime": "Documented",
        "tags": "Pwn, gets(), Struct Overflow, Integer Sign, Logic Abuse",
        "skills": "C Struct Layout · Buffer Overflow · Pwntools · Negative Integer Abuse",
        "date": "2026-06-24",
        "difficulty": "Intro",
        "summary": "Overflowed an order note into the adjacent price field and made the total negative to trigger the flag-printing coupon path.",
        "url": "./kitctf/recipe-for-disaster.html",
        "category": "Pwn"
      },
      {
        "title": "Customer Service",
        "ctf": "kitCTF / GPNCTF",
        "points": "",
        "solves": "",
        "solveTime": "Documented",
        "tags": "Misc, Proof Checker, HOLPy, Logic, Inconsistency",
        "skills": "Program Logic Analysis · Proof Format Crafting · JSON Payloads · Hex Encoding",
        "date": "2026-06-24",
        "difficulty": "Medium",
        "summary": "Abused an inconsistent HOLPy definition to make False provable with no assumptions and trigger the challenge win condition.",
        "url": "./kitctf/customer-service.html",
        "category": "Misc"
      },
      {
        "title": "Pnut-sh / Paradise Nut",
        "ctf": "kitCTF / GPNCTF",
        "points": "",
        "solves": "",
        "solveTime": "Documented",
        "tags": "Misc, Interpreter, File Read, C I/O, Sandbox Escape",
        "skills": "Interpreter Behavior Analysis · File I/O Abuse · Payload Minimization · Remote Interaction",
        "date": "2026-06-24",
        "difficulty": "Easy",
        "summary": "Used supported C file I/O inside a shell-based C interpreter to read /flag directly when system() was unavailable.",
        "url": "./kitctf/pnut-sh.html",
        "category": "Misc"
      },
      {
        "title": "SuperCAT",
        "ctf": "kitCTF / GPNCTF",
        "points": "82",
        "solves": "",
        "solveTime": "Documented",
        "tags": "Misc, SUID, TOCTOU, Symlink Race, Rust",
        "skills": "Linux Enumeration · Race Conditions · SUID Analysis · Symlink Abuse",
        "date": "2026-06-24",
        "difficulty": "Medium",
        "summary": "Won a symlink TOCTOU race against a SUID Rust cat clone by switching a checked readable file into /flag before use.",
        "url": "./kitctf/supercat.html",
        "category": "Misc"
      },
      {
        "title": "Double-fried",
        "ctf": "kitCTF / GPNCTF",
        "points": "",
        "solves": "",
        "solveTime": "Documented",
        "tags": "Forensics, PCAP, Syslog, tshark, Timeline",
        "skills": "Network Forensics · tshark Filtering · Protocol Inspection · Timeline Reconstruction",
        "date": "2026-06-24",
        "difficulty": "Easy",
        "summary": "Extracted syslog messages from a PCAP and reconstructed the flag from ordered single-character records.",
        "url": "./kitctf/double-fried.html",
        "category": "Forensics"
      }
    ]
  }
  ,{
    "id": "sloppedctf",
    "name": "Slopped CTF Writeups",
    "shortName": "Slopped CTF",
    "icon": "🧭",
    "accent": "rgba(88, 166, 255, 0.78)",
    "accentSoft": "rgba(88, 166, 255, 0.26)",
    "description": "A standalone Slopped CTF cabinet containing the completed OSINT and Web casefiles, separated from the other competitions.",
    "tags": [
      "OSINT",
      "Web"
    ],
    "writeups": [
      {
        "title": "Geo Challenge",
        "ctf": "Slopped CTF",
        "points": "",
        "solves": "",
        "solveTime": "Documented",
        "tags": "OSINT, Geolocation, Panorama Analysis, Landmark Matching",
        "skills": "Geolocation OSINT · Visual Clue Analysis · Map Verification · Evidence Documentation",
        "date": "2026-06-24",
        "difficulty": "Medium",
        "summary": "Solved nine worldwide geolocation cards and used the 9/10 progress state as proof to recover the displayed flag.",
        "url": "./sloppedctf/geo-challenge.html",
        "category": "OSINT"
      },
      {
        "title": "SloppedRider",
        "ctf": "Slopped CTF",
        "points": "",
        "solves": "",
        "solveTime": "Documented",
        "tags": "SSRF, Internal Service, HMAC, Token Forgery, Source Review",
        "skills": "Source Code Review · SSRF Exploitation · Internal Service Enumeration · HMAC Ticket Forgery",
        "date": "2026-06-24",
        "difficulty": "Medium",
        "summary": "Chained SSRF into an internal ops-service leak, recovered the score signing key, forged a ride ticket, and submitted the impossible score 676767.",
        "url": "./sloppedctf/sloppedrider.html",
        "category": "Web"
      }
    ]
  }
];
